### ISSUE TITLE
Request for feedback

### ISSUE THREAD

**Issue by josevalim** [antipax/nifsy#1]
Hi @potatosalad!

More developers are using Elixir for data processing and the speed from which we read and write to files has lately been a concern. @antipax decided to explore solutions and one of them is this project: a module that implements file read and write operations as a NIF. For performance, we are reading data into a buffer and then read out of the buffer (similar to Erlang read-ahead). This is considerably faster than Erlang default file handling (that uses a process + port) and about 3x-4x faster than Elixir streams.

The reason we are pinging you is that you have done great work on C libraries so we would love if you could do a code review in your spare time. In particular, we would love to know if we can further optimize our buffer handling, reduce the amount of allocations, etc. 

Thank you! :heart:

**Comment by ericentin** [comment]
Just wanted to share that ATM the library is not even close to done, so I think right now a general review would be better off being postponed until some more work has been completed.

That being said, I think the questions around whether we can further optimize `nifsy_read_line` would be great to get assistance on ASAP if you are interested, @potatosalad!

**Comment by potatosalad** [comment]
@josevalim @antipax Sorry I missed your [ping](https://botbot.me/freenode/elixir-lang/2016-07-21/?msg=69996207), and sure I can take a look at things.

Is there a benchmark or anything like that you are already running locally?

I put together a quick benchmark locally to get a baseline comparison between `:read_line` operations of `:file` and `Nifsy`.  I'm seeing these numbers (with some variation between runs):

| File Size (Read Ahead) | `:file` | `Nifsy` | Lines |
| --: | --: | --: | --: |
| 1 KB (1 KB) | **9.1 μs** | 9.9 μs | 45 |
| 1 MB (1 KB) | 14.6 μs | **9.6 μs** | 1,448 |
| 1 MB (1 MB) | **7.7 μs** | 8.9 μs | 1,448 |
| 1 GB (1 KB) | **25.7 μs** | 26.7 μs | 46,341 |
| 1 GB (1 MB) | 14.1 μs | **13.9 μs** | 46,341 |
| 1 GB (1 GB) | **17.0 μs** | 33.8 μs | 46,341 |

The microseconds in the table above are the average time taken to process each `:read_line` call.  For comparison, running `wc -l gigabyte.txt` takes roughly 24 μs per line.

Here's the benchmark I ran locally:

``` elixir
benchmark_all_the_things = fn () ->
  benchmark = fn (n, function, arguments, cleanup) ->
    bench_loop = fn
      (_, 0, acc_u_sec, _, _, _) ->
        acc_u_sec
      (f, i, acc_u_sec, function, arguments, cleanup) ->
        args = arguments.()
        {u_sec, _} = :timer.tc(function, args)
        cleanup.(args)
        f.(f, i - 1, acc_u_sec + u_sec, function, arguments, cleanup)
    end
    acc_u_sec = bench_loop.(bench_loop, n, 0, function, arguments, cleanup)
    {acc_u_sec, acc_u_sec / n}
  end
  nifsy_read_line_benchmark = fn (n, filename, read_ahead_bytes, num_lines) ->
    read_line_loop = fn (f, file_desc, size) ->
      case Nifsy.read_line(file_desc, read_ahead_bytes) do
        :eof -> size
        line -> f.(f, file_desc, size + byte_size(line) + 1)
      end
    end
    function = fn (file_desc) ->
      read_line_loop.(read_line_loop, file_desc, 0)
    end
    arguments = fn () ->
      {:ok, file_desc} = Nifsy.open(filename)
      [file_desc]
    end
    cleanup = fn ([file_desc]) ->
      Nifsy.close(file_desc)
    end
    {acc_u_sec, avg_u_sec} = benchmark.(n, function, arguments, cleanup)
    {acc_u_sec, avg_u_sec, avg_u_sec / num_lines}
  end
  file_read_line_benchmark = fn (n, filename, read_ahead_bytes, num_lines) ->
    read_line_loop = fn (f, io_device, size) ->
      case :file.read_line(io_device) do
        :eof -> size
        {:ok, line} -> f.(f, io_device, size + byte_size(line))
      end
    end
    function = fn (io_device) ->
      read_line_loop.(read_line_loop, io_device, 0)
    end
    arguments = fn () ->
      {:ok, io_device} = :file.open(filename, [:binary, :raw, :read, {:read_ahead, read_ahead_bytes}])
      [io_device]
    end
    cleanup = fn ([io_device]) ->
      :file.close(io_device)
    end
    {acc_u_sec, avg_u_sec} = benchmark.(n, function, arguments, cleanup)
    {acc_u_sec, avg_u_sec, avg_u_sec / num_lines}
  end
  generate_file_with_lines = fn (filename, file_size) ->
    {:ok, io_device} = :file.open(filename, [:binary, :raw, :write])
    write_loop = fn (f, b, s) ->
      if s + byte_size(b) >= file_size do
        b = :binary.part(b, 0, file_size - s - 1)
        :file.write(io_device, b <> "\n")
        s + byte_size(b) + 1
      else
        :file.write(io_device, b <> "\n")
        f.(f, b <> "0", s + byte_size(b) + 1)
      end
    end
    _write_size = write_loop.(write_loop, "", 0)
    :file.close(io_device)
  end
  maybe_generate_file_with_lines = fn (filename, file_size) ->
    case File.stat(filename) do
      {:ok, %File.Stat{size: ^file_size}} ->
        :ok
      _ ->
        generate_file_with_lines.(filename, file_size)
    end
  end
  for {filename, file_size} <- [
    {"kilobyte.txt", 1024},
    {"megabyte.txt", 1024 * 1024},
    {"gigabyte.txt", 1024 * 1024 * 1024}
  ], do: maybe_generate_file_with_lines.(filename, file_size)
  IO.puts(
    "1ZRLDoIwEED3nAKPomfwAsYQMSILvUAXXczChRHTA/YkUn5T+qEfrInJSBQ7781MKfxNeIpglD" <>
    "PogmZJBMJBRgckc6As1CEmIMX3HYyoXP1OjEPUS8agfc68G8Ce9MVuR5s/mZQ7C4vfUjUejvko" <>
    "+jJDF3vMCrB93z0jE93b4f9QGHOFY9goil9sWzL0tHA15XaO9r+XFGBxgF/QHzhAfQgDHBGaGE" <>
    "eQJn0f/rOaKopoYu4ghhKQGLHtMoFyPIPGkvHogpJmv8rvEvHTJFBkisN9tvuD3JjK19GyAF8E" <>
    "xiAjtzHRbWhc04SETl9qeSXdMdB/pbNnMnoM2pMei+bs4aKnQifhroFmu6I+ltfD7ZJvqyrfl0" <>
    "X7Oden+yb7AA==" |> Base.decode64!() |> :zlib.unzip())
  [
    {"1 KB (1 KB) - nifsy", nifsy_read_line_benchmark.(50, 'kilobyte.txt', 1024, 45)},
    {"1 MB (1 KB) - nifsy", nifsy_read_line_benchmark.(50, 'megabyte.txt', 1024, 1448)},
    {"1 MB (1 MB) - nifsy", nifsy_read_line_benchmark.(50, 'megabyte.txt', 1024 * 1024, 1448)},
    {"1 GB (1 KB) - nifsy", nifsy_read_line_benchmark.(10, 'gigabyte.txt', 1024, 46341)},
    {"1 GB (1 MB) - nifsy", nifsy_read_line_benchmark.(10, 'gigabyte.txt', 1024 * 1024, 46341)},
    {"1 GB (1 GB) - nifsy", nifsy_read_line_benchmark.(10, 'gigabyte.txt', 1024 * 1024 * 1024, 46341)},
    {"1 KB (1 KB) - file", file_read_line_benchmark.(50, 'kilobyte.txt', 1024, 45)},
    {"1 MB (1 KB) - file", file_read_line_benchmark.(50, 'megabyte.txt', 1024, 1448)},
    {"1 MB (1 MB) - file", file_read_line_benchmark.(50, 'megabyte.txt', 1024 * 1024, 1448)},
    {"1 GB (1 KB) - file", file_read_line_benchmark.(10, 'gigabyte.txt', 1024, 46341)},
    {"1 GB (1 MB) - file", file_read_line_benchmark.(10, 'gigabyte.txt', 1024 * 1024, 46341)},
    {"1 GB (1 GB) - file", file_read_line_benchmark.(10, 'gigabyte.txt', 1024 * 1024 * 1024, 46341)}
  ]
end
benchmark_all_the_things.()
```

I'll review the code more closely and see if there are any optimizations that can help speed things up.

**Comment by josevalim** [comment]
@potatosalad your benchmark looks awesome. Maybe we should even tidy it up and include it in the repo. :D I would only change it so we run each benchmark in a new task so we don't have garbage generated by one task affecting the other as well as measure 64k buffers:

``` elixir
  [
    {"1 KB (1 KB) - nifsy", Task.async(fn -> nifsy_read_line_benchmark.(50, 'kilobyte.txt', 1024, 45) end) |> Task.await(60_000)},
    {"1 KB (64KB) - nifsy", Task.async(fn -> nifsy_read_line_benchmark.(50, 'kilobyte.txt', 65536, 45) end) |> Task.await(60_000)},
    {"1 MB (1 KB) - nifsy", Task.async(fn -> nifsy_read_line_benchmark.(50, 'megabyte.txt', 1024, 1448) end) |> Task.await(60_000)},
    {"1 MB (64KB) - nifsy", Task.async(fn -> nifsy_read_line_benchmark.(50, 'megabyte.txt', 65536, 1448) end) |> Task.await(60_000)},
    {"1 MB (1 MB) - nifsy", Task.async(fn -> nifsy_read_line_benchmark.(50, 'megabyte.txt', 1024 * 1024, 1448) end) |> Task.await(60_000)},
    {"1 GB (1 KB) - nifsy", Task.async(fn -> nifsy_read_line_benchmark.(10, 'gigabyte.txt', 1024, 46341) end) |> Task.await(60_000)},
    {"1 GB (64KB) - nifsy", Task.async(fn -> nifsy_read_line_benchmark.(10, 'gigabyte.txt', 65536, 46341) end) |> Task.await(60_000)},
    {"1 GB (1 MB) - nifsy", Task.async(fn -> nifsy_read_line_benchmark.(10, 'gigabyte.txt', 1024 * 1024, 46341) end) |> Task.await(60_000)},
    {"1 GB (1 GB) - nifsy", Task.async(fn -> nifsy_read_line_benchmark.(10, 'gigabyte.txt', 1024 * 1024 * 1024, 46341) end) |> Task.await(60_000)},
    {"1 KB (1 KB) - file", Task.async(fn -> file_read_line_benchmark.(50, 'kilobyte.txt', 1024, 45) end) |> Task.await(60_000)},
    {"1 KB (64KB) - file", Task.async(fn -> file_read_line_benchmark.(50, 'kilobyte.txt', 65536, 45) end) |> Task.await(60_000)},
    {"1 MB (1 KB) - file", Task.async(fn -> file_read_line_benchmark.(50, 'megabyte.txt', 1024, 1448) end) |> Task.await(60_000)},
    {"1 MB (64KB) - file", Task.async(fn -> file_read_line_benchmark.(50, 'megabyte.txt', 65536, 1448) end) |> Task.await(60_000)},
    {"1 MB (1 MB) - file", Task.async(fn -> file_read_line_benchmark.(50, 'megabyte.txt', 1024 * 1024, 1448) end) |> Task.await(60_000)},
    {"1 GB (1 KB) - file", Task.async(fn -> file_read_line_benchmark.(10, 'gigabyte.txt', 1024, 46341) end) |> Task.await(60_000)},
    {"1 GB (64KB) - file", Task.async(fn -> file_read_line_benchmark.(10, 'gigabyte.txt', 65536, 46341) end) |> Task.await(60_000)},
    {"1 GB (1 MB) - file", Task.async(fn -> file_read_line_benchmark.(10, 'gigabyte.txt', 1024 * 1024, 46341) end) |> Task.await(60_000)},
    {"1 GB (1 GB) - file", Task.async(fn -> file_read_line_benchmark.(10, 'gigabyte.txt', 1024 * 1024 * 1024, 46341) end) |> Task.await(60_000)}
  ]
```

Here are my results:

| File Size (Read Ahead) | :file | Nifsy |
| --- | --- | --- |
| 1 KB (1 KB) | 7071 | 880 |
| 1 KB (64KB) | 4255 | 940 |
| 1 MB (1 KB) | 1_655_035 | 93_341 |
| 1 MB (64KB) | 103_770 | 35_039 |
| 1 MB (1 MB) | 218_306 | 66_683 |
| 1 GB (1 KB) | 15_148_203 | 11_834_354 |
| 1 GB (64KB) | 10_223_941 | 2_912_475 |
| 1 GB (1 MB) | 4_146_416 | 3_372_529 |
| 1 GB (1 GB) | 5_858_421 | 10_363_939 |

Those are total times in us. Nifsy is faster in all cases except for the 1GB buffer. 64kb seems to be a reasonable default buffer size.

**Comment by ericentin** [comment]
This is awesome! I'm going to add the benchmark to the repo. I also added you both as collaborators on the repo, just in case either of you want to add anything in the future.

**Comment by ericentin** [comment]
hahhahah the zipped ASCII art is amazing @potatosalad

**Comment by ericentin** [comment]
Ok, cleaned up the bench a bit and put it in the repo. Had to remove the ASCII art unfortunately because it made it hard to compare runs. :(

Going to work on implementing the rest of the ops and general code cleanup now.

**Comment by potatosalad** [comment]
@antipax I added a tiny commit to ensure the `tmp` directory exists before generating the test files.  Hopefully that's okay git-etiquette-wise.

**Comment by ericentin** [comment]
@potatosalad yup, that's fine, just don't force push to master! :)

**Comment by ericentin** [comment]
So, interestingly, after testing with dirty NIFs enabled, performance improvement is not as good (the chart in the README currently is with dirty disabled):

```
name                    total           usec/iter       usec/line
1 KB (1 KB) - nifsy     10226           204.52          4.545
1 KB (1 KB) - file      8327            166.54          3.701
1 KB (64KB) - nifsy     11475           229.5           5.1
1 KB (64KB) - file      6298            125.96          2.799
1 MB (1 KB) - nifsy     329999          6599.98         4.558
1 MB (1 KB) - file      1545261         30905.22        21.343
1 MB (64KB) - nifsy     249440          4988.8          3.445
1 MB (64KB) - file      124039          2480.78         1.713
1 MB (1 MB) - nifsy     273761          5475.22         3.781
1 MB (1 MB) - file      96324           1926.48         1.33
1 GB (1 KB) - nifsy     14660091        1466009.1       31.635
1 GB (1 KB) - file      17172250        1717225.0       37.056
1 GB (64KB) - nifsy     5436278         543627.8        11.731
1 GB (64KB) - file      11375785        1137578.5       24.548
1 GB (1 MB) - nifsy     6346453         634645.3        13.695
1 GB (1 MB) - file      4520818         452081.8        9.756
1 GB (1 GB) - nifsy     37860721        3786072.1       81.7
1 GB (1 GB) - file      33788830        3378883.0       72.913
```

So, at 1GB (64KB)  our perf improvement drops to 2x, from 4x without dirtiness.

I am not sure why this is the case, but currently my theory is that regular NIFs just run on whatever thread the BEAM is currently using, and dirty NIFs have to get a thread from the dirty scheduler, which may involve overhead in the form of synchronization and extra copying. Do you guys have any thoughts?

**Comment by josevalim** [comment]
> I am not sure why this is the case, but currently my theory is that regular NIFs just run on whatever thread the BEAM is currently using, and dirty NIFs have to get a thread from the dirty scheduler, which may involve overhead in the form of synchronization and extra copying.

That's exactly it. We must play nicely with the VM. We need to figure out if we can further optimize the C the code, otherwise I am afraid there isn't much we can do?

**Comment by ericentin** [comment]
One thing I'm wondering about is why certain combos seem to do so much better:

```
1 MB (1 KB) - nifsy     329999          6599.98         4.558
1 MB (1 KB) - file      1545261         30905.22        21.343
```

```
1 GB (64KB) - nifsy     5436278         543627.8        11.731
1 GB (64KB) - file      11375785        1137578.5       24.548
```

perhaps changing the NIF to return as many lines per-read-ahead as it can at once, and then returning them in a list for read_line would avoid some of the overhead?

**Comment by ericentin** [comment]
I just pushed a major cleanup/optimization with `read`/`close` implemented. I still have to do `write` and clean up/document the Elixir side of things, as well. We now only allocate the buffer once and never resize it, ever, by tracking the actual amount of data in the buffer instead of resizing it when there is a less than buffer-size amount of data.

**Comment by potatosalad** [comment]
I'm not sure which of the following strategies might result in the best performance, especially in a heavily concurrent context.
1. (+2) Optimized combination of 1 and 2 listed below.
2. (+1) NIF with non-blocking I/O and event loop in a separate thread using [`enif_thread_create()`](http://erlang.org/doc/man/erl_nif.html#enif_thread_create)
3. (+1) NIF with non-blocking I/O and timeslice reductions using [`enif_consume_timeslice()`](http://erlang.org/doc/man/erl_nif.html#enif_consume_timeslice) and [`enif_schedule_nif()`](http://erlang.org/doc/man/erl_nif.html#enif_schedule_nif)
4. (+?) Port Driver with non-blocking I/O using [`driver_select()`](http://erlang.org/doc/man/erl_driver.html#driver_select) (at that point, however, we're potentially doing the same thing that [`efile_drv`](https://github.com/erlang/otp/blob/OTP-19.0/erts/emulator/drivers/common/efile_drv.c) is doing)
5. (+?) C Port with non-blocking I/O and event loop in a separate process
6. (-1) NIF with blocking I/O and dirty schedulers
7. (-1) NIF with blocking I/O

**Comment by ericentin** [comment]
Just implemented `write` for our current simple strategy, and planning to flesh out the OTP API before moving onto doing the libuv-based implementation like we discussed, partly so we have something to compare to, and partly so anyone who needs fast FS ops for OTP has this as an option, regardless of when we finish the more complicated/better solution.

Going to be working on the OTP API as I mentioned, so @potatosalad if you want to play around with the libuv stuff go ahead. I'll drop a note here before I try to get started with that.
