### ISSUE TITLE
Reading an audio files.

### ISSUE THREAD

**Issue by max-konin** [antipax/nifsy#3]
Hello. I try to read an audio file for later sending  to external service.And the data is corrupted while reading

Simple example:
```elixir
"path/to/input/file.wav"
|> Nifsy.stream!()
|> Stream.into(File.stream!("path/to/output/file.wav"))
|> Stream.run()
```

The output file has a noise

**Comment by josevalim** [comment]
Btw, Erlang/OTP 21 has moved their file operations to NIFs, so the benefits of using this library may have been reduced a bit. :)

**Comment by max-konin** [comment]
@josevalim thank you for quick answer. OTP 21 works fine
